name: CI

on:
  push:
    branches: ['**']
    tags: [v*]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Java / Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 11

      - name: Cache Scala Libraries
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Cache Docker Layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Import GPG key & set Git config
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSWORD }}
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-tag-gpgsign: true
          git-push-gpgsign: false

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint, Test, Bump & Deploy
        run: sbt deploySnapshot
        env:
          DOCKER_REPOSITORY: ghcr.io
          DOCKER_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash



